### ISSUE TITLE
"build" error about Jabba

### ISSUE THREAD

**Issue by meibinbin** [gmiclotte/Jabba#1]
Hello,
I run into the following problems when I build the Jabba.
Scanning dependencies of target Jabba
[  8%] Building CXX object src/CMakeFiles/Jabba.dir/GraphChain.cpp.o
cc1plus: error: unrecognized command line option ‘-std=c++11’
make[2]: **\* [src/CMakeFiles/Jabba.dir/GraphChain.cpp.o] Error 1
make[1]: **\* [src/CMakeFiles/Jabba.dir/all] Error 2
make: **\* [all] Error 2
cp: cannot stat `./build/src/Jabba': No such file or directory
I hope you can help me to solve this problem.Thank you.

**Comment by gmiclotte** [comment]
Hello,

what version of GCC are you using?
The problem is that your compiler does not recognise the option -std=c++11. If you use GCC 4.7 or a more recent version, this should fix the problem.

Kind regards,
Giles
