### ISSUE TITLE
Core dumped 

### ISSUE THREAD

**Issue by RP0427** [gmiclotte/Jabba#3]
Input  uncorrected long read file: main_l.fastq

./bin/jabba -o out -l 20 -k 75 -p 2 -e 1 -g brownie_data/DBGraph.fasta -fastq main_l.fastq

FileType is fastq.
Max Number of Threads is 4
Graph is brownie_data/DBGraph.fasta
DBG K is 75
ESSA K is 1
Max Passes is 2
Min Seed Size is 20
Output Directory is out
Output Mode is short
Reading the graph... 
Done.
Constructing ESSA... 
atempting to load index out/DBGraph_1_1_1 ... 
index loaded succesful
Done.
INDEX SIZE IN BYTES: 19125733
Number of threads: 4
Worker threads started.
Processing file 1/1: main_l.fastq, type: fastq
Number of reads processed: 4005
terminate called after throwing an instance of 'std::out_of_range'
what():  basic_string::substr: __pos (which is 74) > this->size() (which is 19)
terminate called recursively
Aborted (core dumped)

I don't get it, why core dumped. Is it specific to my DBGraph.fasta?  please help.
[brownie_data.zip](https://github.com/gmiclotte/Jabba/files/289144/brownie_data.zip)

Thanks

**Comment by gmiclotte** [comment]
Hi,

your DBG was built with k=19, hence you should tell Jabba to use k=19 and not k=75. But, I would advise to use a higher k-mer size than 19.

Giles

**Comment by RP0427** [comment]
Thanks, it worked. All the time I was thinking my DBG was built with k=75.
